// <auto-generated />
using System;
using ClubDeportivoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubDeportivoApp.Migrations
{
    [DbContext(typeof(ClubDbContext))]
    partial class ClubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClubDeportivoApp.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("ColorIdentificador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EntrenadorId")
                        .IsUnique();

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Participantes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Entrenador", b =>
                {
                    b.HasBaseType("ClubDeportivoApp.Models.Participante");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Entrenadores", (string)null);
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Jugador", b =>
                {
                    b.HasBaseType("ClubDeportivoApp.Models.Participante");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("PosicionDeJuego")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Equipo", b =>
                {
                    b.HasOne("ClubDeportivoApp.Models.Entrenador", "Entrenador")
                        .WithOne("EquipoDirigido")
                        .HasForeignKey("ClubDeportivoApp.Models.Equipo", "EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Entrenador", b =>
                {
                    b.HasOne("ClubDeportivoApp.Models.Participante", null)
                        .WithOne()
                        .HasForeignKey("ClubDeportivoApp.Models.Entrenador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Jugador", b =>
                {
                    b.HasOne("ClubDeportivoApp.Models.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClubDeportivoApp.Models.Participante", null)
                        .WithOne()
                        .HasForeignKey("ClubDeportivoApp.Models.Jugador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("ClubDeportivoApp.Models.Entrenador", b =>
                {
                    b.Navigation("EquipoDirigido");
                });
#pragma warning restore 612, 618
        }
    }
}
